/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

module demux_generate(o0, o1, o2, o3, o4, o5, o6, o7, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  input i;
  wire [31:0] k;
  output o0;
  output o1;
  output o2;
  output o3;
  output o4;
  output o5;
  output o6;
  output o7;
  input [2:0] sel;
  wire [7:0] y_int;
  sky130_fd_sc_hd__and4_1 _25_ (
    .A(_24_),
    .B(_23_),
    .C(_22_),
    .D(_13_),
    .X(_21_)
  );
  sky130_fd_sc_hd__and4b_1 _26_ (
    .A_N(_22_),
    .B(_13_),
    .C(_24_),
    .D(_23_),
    .X(_20_)
  );
  sky130_fd_sc_hd__and4b_1 _27_ (
    .A_N(_23_),
    .B(_22_),
    .C(_13_),
    .D(_24_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nor4b_1 _28_ (
    .A(_24_),
    .B(_23_),
    .C(_22_),
    .D_N(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor4bb_1 _29_ (
    .A(_24_),
    .B(_23_),
    .C_N(_22_),
    .D_N(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__and4b_1 _30_ (
    .A_N(_24_),
    .B(_23_),
    .C(_22_),
    .D(_13_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nor4bb_1 _31_ (
    .A(_23_),
    .B(_22_),
    .C_N(_13_),
    .D_N(_24_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor4bb_1 _32_ (
    .A(_24_),
    .B(_22_),
    .C_N(_13_),
    .D_N(_23_),
    .Y(_16_)
  );
  assign k = 32'd8;
  assign y_int = { o7, o6, o5, o4, o3, o2, o1, o0 };
  assign _24_ = sel[2];
  assign _23_ = sel[1];
  assign _22_ = sel[0];
  assign _13_ = i;
  assign o7 = _21_;
  assign o6 = _20_;
  assign o5 = _19_;
  assign o0 = _14_;
  assign o1 = _15_;
  assign o3 = _17_;
  assign o4 = _18_;
  assign o2 = _16_;
endmodule
